import CRoute from '../types/CRoute'
import {
  ProfileManager,
  SubmittedProfile,
  Page404,
  Page500,
  ShowAchievementUser,
  Auditor,
  AuditorFinal,
  AchievementTabs,
  FormStudent,
  FormManager,
  ParticipantManagement,
  UserSubmission,
  submissionUsers,
  SubmissionUsersTest,
  AuditorFinalTest,
  AchievementPage,
  CriteriaPage,
  DepartmentManagerIndexPage,
  SubmissionPage,
  ManageAuditor,
  ShowHistoryAchievement,
  SubmissionUsersFaculty,
  AchievementStatistic,
  ExpertisePage,
  ExpertiseProfilePage,
  SubmissionUsersResult,
  ExportReport,
  ReportedProfile,
  ResultDetail,
  SubmissionUsersTestFinal,
} from './routes'
const routes: CRoute[] = [
  { path: '/danh-hieu', exact: true, component: AchievementPage },
  { path: '/tham-tra', exact: true, component: ExpertisePage },
  { path: '/tham-tra-danh-hieu/:id', exact: true, component: ExpertiseProfilePage },
  { path: '/thong-ke-danh-hieu/:id', exact: true, component: AchievementStatistic },
  { path: '/quan-ly-danh-hieu-cap-don-vi', exact: true, component: ProfileManager },
  { path: '/xem-ket-qua-tham-dinh', exact: true, component: ExportReport },
  { path: '/quan-ly-tieu-chi/:id', exact: true, component: CriteriaPage },
  { path: '/de-cu', exact: true, component: ShowAchievementUser },
  { path: '/lich-su-de-cu', exact: true, component: ShowHistoryAchievement },
  { path: '/auditor', exact: true, component: Auditor },
  { path: '/auditor-final/:id', exact: true, component: AuditorFinal },
  { path: '/danh-sach-nop-ho-so/:id', exact: true, component: UserSubmission },
  { path: '/danh-sach-nop-ho-so-cap-don-vi/:id', exact: true, component: SubmittedProfile },
  { path: '/danh-sach-ket-qua-tham-dinh/:id', exact: true, component: ReportedProfile },
  { path: '/chi-tiet-ho-so/:id', exact: true, component: submissionUsers },
  {
    path: '/tham-dinh-ho-so/:id/:mssv',
    exact: true,
    component: SubmissionUsersTest,
  },
  {
    path: '/ket-luan-tham-dinh-ho-so/:id/:mssv',
    exact: true,
    component: SubmissionUsersTestFinal,
  },
  {
    path: '/ket-qua-ho-so/:id/:mssv',
    exact: true,
    component: SubmissionUsersResult,
  },
  {
    path: '/duyet-ho-so-cap-don-vi/:id/:mssv',
    exact: true,
    component: SubmissionUsersFaculty,
  },
  {
    path: '/ket-qua-tham-dinh/:id/:mssv',
    exact: true,
    component: ResultDetail,
  },
  {
    path: '/chu-tich-duyet-ho-so/:id/:mssv',
    exact: true,
    component: AuditorFinalTest,
  },

  {
    path: '/quan-li-nguoi-dung',
    exact: true,
    component: ParticipantManagement,
  },
  { path: '/thong-tin', exact: true, component: FormStudent },
  { path: '/thong-tin-can-bo', exact: true, component: FormManager },
  {
    path: '/cham-bai/:id',
    exact: true,
    component: AchievementTabs,
  },
  { path: '/loi-truy-cap', exact: true, component: Page500 },
  {
    path: '/department-manager',
    exact: true,
    component: DepartmentManagerIndexPage,
  },
  {
    path: '/de-cu/:id',
    exact: true,
    component: SubmissionPage,
  },
  {
    path: '/quan-ly-hoi-dong-tham-dinh/:id',
    exact: true,
    component: ManageAuditor,
  },
  { path: '/not-found', exact: true, component: Page404 },
]

export default routes
